#!/usr/bin/env bash

CONTAINER=beluga-registry
REGISTRY_VERSION=2.7.1

docker start "$CONTAINER" >/dev/null 2>&1 || docker run -d -p 5000:5000 --restart=always --name "$CONTAINER" "registry:$REGISTRY_VERSION"

repush() {
local to="localhost:5000/$1"
docker pull "$1"
docker tag "$1" "$to"
docker push "$to"
}

repush alpine:3.5
repush busybox:1.31
repush busybox:1.30
